### ISSUE TITLE
多选日期设置selectedDateTimeList会报错

### ISSUE THREAD

**Issue by 6ag** [fluttercandies/flutter_custom_calendar#24]
控制器初始化代码：
```dart
_controller = CalendarController(
      selectMode: CalendarConstants.MODE_MULTI_SELECT,
      minSelectYear: minSelectDate.year,
      minSelectMonth: minSelectDate.month,
      minSelectDay: minSelectDate.day,
      maxSelectYear: maxSelectDate.year,
      maxSelectMonth: maxSelectDate.month,
      maxSelectDay: maxSelectDate.day,
      selectedDateTimeList: selectedDates,
    );
```

`widget.selectedDates`为空Set的时候正常，一旦有值，就直接报错。下面是错误信息：
```shell
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building NotificationListener<DraggableScrollableNotification>:
The method 'addAll' was called on null.
Receiver: null
Tried calling: addAll(Instance of '_CompactLinkedHashSet<DateModel>')

User-created ancestor of the error-causing widget was: 
  MaterialApp file:///Users/feng/Work/sobenapp/lib/main.dart:147:12
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      new CalendarController (package:flutter_custom_calendar/controller.dart:80:12)
#2      _MultiSelectDateWidgetState.initState (package:sobenapp/widget/repayment/rment_date_picker.dart:86:18)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
...
```

根据错误日志提示，我找到了报错的地方：
```dart
if (selectedDateTimeList != null && selectedDateTimeList.isNotEmpty) {
    calendarConfiguration.defaultSelectedDateList
        .addAll(selectedDateTimeList.map((dateTime) {
    return DateModel.fromDateTime(dateTime);
    }).toSet());
}
```

我在初始化`CalendarController`的时候不传`selectedDateTimeList`，然后打印`_controller.calendarConfiguration.defaultSelectedDateList`，发现是`null`。

但是查看源码，默认是有初始化的，也没有发现有其他地方重新赋值。
```dart
Set<DateModel> defaultSelectedDateList = new Set(); //默认被选中的日期
```

大佬帮忙看看是怎么回事，谢谢。

**Comment by 6ag** [comment]
最新发现，我去掉我项目中使用的`provide`后，就没有报错了，但是我设置的`selectedDateTimeList `也没有效果。
```dart
//  runApp(ProviderNode(
//    child: MyApp(),
//    providers: providers,
//  ));
  runApp(MyApp());
```
就算是我把这个插件里的`CalendarProvider`配置到我项目中的`provide`，也会报错同样的错误。
```dart
final providers = Providers()
..provide(Provider.function((context) => CalendarProvider()));

runApp(ProviderNode(
child: MyApp(),
providers: providers,
));
```
大佬看看这些信息有帮助没。

**Comment by LXD312569496** [comment]
嗯嗯，我知道原因了，后面代码优化，这部分没赋值，所以有问题。我明天中午前把代码提交搞上去。

**Comment by 6ag** [comment]
> 嗯嗯，我知道原因了，后面代码优化，这部分没赋值，所以有问题。我明天中午前把代码提交搞上去。

谢谢大佬，在线等，不是很急的

**Comment by LXD312569496** [comment]
嗯嗯，我的代码更新了，自测通过，你看看有没有问题

**Comment by 6ag** [comment]
> 嗯嗯，我的代码更新了，自测通过，你看看有没有问题

谢谢大佬，测试已经解决，完美
